"""Model registry seed used by the test suite: offline mock models plus legacy paid entries."""

from app.schemas.models import ModelMetadata, ModelTier, ModelType

TEST_MODELS: list[ModelMetadata] = [
    ModelMetadata(
        id="gpt-4o-mini",
        name="GPT-4o Mini",
        provider="openai",
        type=ModelType.API,
        tier=ModelTier.SMALL,
        input_cost_per_1m_tokens=0.15,
        output_cost_per_1m_tokens=0.60,
        context_window=128000,
        capabilities=["general", "coding", "summarization", "extraction"],
        supports_vision=True,
        supports_tools=True,
        enabled=True,
        avg_latency_ms=450,
        quality_score=0.82,
    ),
    ModelMetadata(
        id="gpt-4o",
        name="GPT-4o",
        provider="openai",
        type=ModelType.API,
        tier=ModelTier.MEDIUM,
        input_cost_per_1m_tokens=2.50,
        output_cost_per_1m_tokens=10.00,
        context_window=128000,
        capabilities=["general", "coding", "reasoning", "summarization"],
        supports_vision=True,
        supports_tools=True,
        enabled=True,
        avg_latency_ms=900,
        quality_score=0.92,
    ),
    ModelMetadata(
        id="gpt-4-turbo",
        name="GPT-4 Turbo",
        provider="openai",
        type=ModelType.API,
        tier=ModelTier.STRONG,
        input_cost_per_1m_tokens=10.00,
        output_cost_per_1m_tokens=30.00,
        context_window=128000,
        capabilities=["general", "coding", "reasoning", "creative_writing"],
        supports_vision=True,
        supports_tools=True,
        enabled=True,
        avg_latency_ms=1400,
        quality_score=0.96,
    ),
    ModelMetadata(
        id="claude-3-haiku",
        name="Claude 3 Haiku",
        provider="anthropic",
        type=ModelType.API,
        tier=ModelTier.SMALL,
        input_cost_per_1m_tokens=0.25,
        output_cost_per_1m_tokens=1.25,
        context_window=200000,
        capabilities=["general", "summarization", "extraction", "classification"],
        supports_vision=True,
        supports_tools=True,
        enabled=False,
        avg_latency_ms=400,
        quality_score=0.80,
    ),
    ModelMetadata(
        id="claude-3-5-sonnet",
        name="Claude 3.5 Sonnet",
        provider="anthropic",
        type=ModelType.API,
        tier=ModelTier.MEDIUM,
        input_cost_per_1m_tokens=3.00,
        output_cost_per_1m_tokens=15.00,
        context_window=200000,
        capabilities=["general", "coding", "reasoning", "creative_writing"],
        supports_vision=True,
        supports_tools=True,
        enabled=False,
        avg_latency_ms=950,
        quality_score=0.94,
    ),
    ModelMetadata(
        id="openai/gpt-oss-20b",
        name="GPT-OSS 20B (Groq)",
        provider="groq",
        type=ModelType.API,
        tier=ModelTier.SMALL,
        input_cost_per_1m_tokens=0.075,
        output_cost_per_1m_tokens=0.30,
        context_window=131072,
        capabilities=["general", "coding", "summarization"],
        supports_vision=False,
        supports_tools=True,
        enabled=True,
        avg_latency_ms=1200,
        quality_score=0.82,
    ),
    ModelMetadata(
        id="gemini-3.5-flash-lite",
        name="Gemini 3.5 Flash-Lite",
        provider="google",
        type=ModelType.API,
        tier=ModelTier.MEDIUM,
        input_cost_per_1m_tokens=0.30,
        output_cost_per_1m_tokens=2.50,
        context_window=1000000,
        capabilities=["general", "coding", "summarization", "translation"],
        supports_vision=False,
        supports_tools=False,
        enabled=True,
        avg_latency_ms=1600,
        quality_score=0.87,
    ),
    ModelMetadata(
        id="gemini-3.5-flash",
        name="Gemini 3.5 Flash",
        provider="google",
        type=ModelType.API,
        tier=ModelTier.STRONG,
        input_cost_per_1m_tokens=1.50,
        output_cost_per_1m_tokens=9.00,
        context_window=1000000,
        capabilities=["general", "coding", "reasoning", "creative_writing"],
        supports_vision=False,
        supports_tools=False,
        enabled=True,
        avg_latency_ms=10000,
        quality_score=0.95,
    ),
    ModelMetadata(
        id="nvidia/nemotron-3-super-120b-a12b:free",
        name="Nemotron 3 Super 120B (OpenRouter)",
        provider="openai_compatible",
        type=ModelType.API,
        tier=ModelTier.MEDIUM,
        input_cost_per_1m_tokens=0.08,
        output_cost_per_1m_tokens=0.45,
        context_window=262144,
        capabilities=["general", "coding", "reasoning", "summarization"],
        supports_vision=False,
        supports_tools=False,
        enabled=True,
        avg_latency_ms=2100,
        quality_score=0.88,
    ),
    ModelMetadata(
        id="mock-echo",
        name="Mock Echo (Local)",
        provider="mock",
        type=ModelType.LOCAL,
        tier=ModelTier.SMALL,
        input_cost_per_1m_tokens=0.0,
        output_cost_per_1m_tokens=0.0,
        context_window=32000,
        capabilities=["general", "coding", "reasoning"],
        enabled=True,
        avg_latency_ms=50,
        quality_score=0.91,
    ),
    ModelMetadata(
        id="mock-echo-medium",
        name="Mock Echo Medium (Local)",
        provider="mock",
        type=ModelType.LOCAL,
        tier=ModelTier.MEDIUM,
        input_cost_per_1m_tokens=0.0,
        output_cost_per_1m_tokens=0.0,
        context_window=32000,
        capabilities=["general", "coding", "reasoning"],
        enabled=True,
        avg_latency_ms=75,
        quality_score=0.92,
    ),
    ModelMetadata(
        id="mock-echo-strong",
        name="Mock Echo Strong (Local)",
        provider="mock",
        type=ModelType.LOCAL,
        tier=ModelTier.STRONG,
        input_cost_per_1m_tokens=0.0,
        output_cost_per_1m_tokens=0.0,
        context_window=32000,
        capabilities=["general", "coding", "reasoning", "creative_writing"],
        enabled=True,
        avg_latency_ms=100,
        quality_score=0.96,
    ),
]
